language: go
sudo: false
go:
  - tip
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go get github.com/mattn/goveralls
script:
  # - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...
